### PR TITLE
updating url checker with 404 fix

### PR DESCRIPTION
**Pull request by carriewright11**
Adding the change here - I noticed there was one other small difference in the script from the main template (just checking that resource dir exists).

But perhaps @cansavvy you want to sync this instead.

### CODE REVIEW

**Comment by cansavvy** [comment]
`check_reports` is the new folder and what OTTR should be saving things to now, saving reports to `resources` is outdated now.

**Review by cansavvy — APPROVED** [review]
Looks good to me!

**Comment by carriewright11** [comment]
> `check_reports` is the new folder and what OTTR should be saving things to now, saving reports to `resources` is outdated now.

yeah I think the resouce dir check was for the ignore-urls.txt file

**Comment by carriewright11** [comment]
> > `check_reports` is the new folder and what OTTR should be saving things to now, saving reports to `resources` is outdated now.
> 
> yeah I think the resource dir check was for the ignore-urls.txt file

do we need that file here?

**Comment by carriewright11** [comment]
> > > `check_reports` is the new folder and what OTTR should be saving things to now, saving reports to `resources` is outdated now.
> > 
> > 
> > yeah I think the resource dir check was for the ignore-urls.txt file
> 
> do we need that file here?

Looks like it was just for: 
https://www.someurl.html
https://jhudatascience.org/{Course_Name}}

So I would think we don't need that here - since we don't have examples like that (I don't think but will double check) 

maybe this: https://username.github.io/repository_name/

**Comment by cansavvy** [comment]
We need to still check for the resources directory. And if there is no ignore-urls.txt file it downloads that dummy one to use. But it isn't committed to the working branch, just to the preview one.

**Comment by carriewright11** [comment]
> We need to still check for the resources directory. And if there is no ignore-urls.txt file it downloads that dummy one to use. But it isn't committed to the working branch, just to the preview one.

Ah ok, gotcha

**Pull request merged**
